# Generated by Django 5.2.17 on 2026-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('organization_id', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('onboarding_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student_onboarding',
            },
        ),
    ]
